name: Backend Continuous Integration

on:
  pull_request:
    branches: [master]
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - run: pip install pipenv
      - run: pipenv install
      - run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - run: pip install pipenv
      - run: pipenv install
      - run: pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/backend

    steps:
      - uses: actions/checkout@v4

      - run: docker build -t mp-backend:ci-test .